name: 'Apply Device-Specific Patches'
description: 'Apply WiFi/Bluetooth fixes for Samsung and Xiaomi 6.6 GKI devices'
inputs:
  kernel_version:
    description: 'Kernel version (e.g., 6.6)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Fix WiFi and Bluetooth on Samsung 6.6 GKI Devices
      if: ${{ inputs.kernel_version == '6.6' }}
      shell: bash
      working-directory: ${{ github.workspace }}/kernel/common
      run: |
        SYMBOL_LIST=android/abi_gki_aarch64_galaxy
        echo "kdp_set_cred_non_rcu" >> $SYMBOL_LIST
        echo "kdp_usecount_dec_and_test" >> $SYMBOL_LIST
        echo "kdp_usecount_inc" >> $SYMBOL_LIST

        PATCH="${{ github.workspace }}/kernel_patches/samsung/min_kdp/add-min_kdp-symbols.patch"
        if patch -p1 --dry-run < "$PATCH"; then
          patch -p1 --no-backup-if-mismatch < $PATCH
        fi

        cp "${{ github.workspace }}/kernel_patches/samsung/min_kdp/min_kdp.c" drivers/min_kdp.c
        echo "obj-y += min_kdp.o" >> drivers/Makefile

    - name: Fix WiFi and Bluetooth on Xiaomi 6.6 GKI Devices
      if: ${{ inputs.kernel_version == '6.6' }}
      shell: bash
      working-directory: ${{ github.workspace }}/kernel/common
      run: |
        SYMBOL_LIST=android/abi_gki_aarch64_xiaomi
        echo "device_find_any_child" >> $SYMBOL_LIST
