name: Setup RFKILL Modules
description: Configure WiFi/Bluetooth RFKILL modules for Hakan variant

runs:
  using: composite
  steps:
    - name: Configure RFKILL for WiFi/Bluetooth
      shell: bash
      working-directory: ${{ github.workspace }}/kernel
      run: |
        cat >> "${{ github.workspace }}/wild_gki.fragment" << 'EOF'
        CONFIG_RFKILL=y
        CONFIG_CFG80211=y
        CONFIG_MAC80211=y
        EOF

        # Remove libarc4.ko and rfkill.ko from modules list
        sed -i \
          -e '/_COMMON_GKI_MODULES_LIST = \[/,/^[[:space:]]*\]/{/^[[:space:]]*"lib\/crypto\/libarc4\.ko",[[:space:]]*$/d}' \
          -e '/_COMMON_GKI_MODULES_LIST = \[/,/^[[:space:]]*\]/{/^[[:space:]]*"net\/rfkill\/rfkill\.ko",[[:space:]]*$/d}' \
          common/modules.bzl
