name: 'Clean Kernel Flags'
description: 'Clean dirty flags and ABI exports to prevent build errors'

runs:
  using: "composite"
  steps:
    - name: Clean Dirty Flags and ABI Exports
      shell: bash
      working-directory: ${{ github.workspace }}/kernel
      run: |
        # Clean dirty flags and ABI exports based on build system
        if [ -f "build/build.sh" ]; then
          # Old build system (5.10, 5.15, early 6.1)
          sed -i 's/-dirty//' ./common/scripts/setlocalversion
        else
          # Bazel build system (newer kernels)
          sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
          sed -i 's/-dirty//' ./common/scripts/setlocalversion
          # Remove ABI protected exports to prevent build errors
          rm -rf ./common/android/abi_gki_protected_exports_*
          perl -pi -e 's/^\s*"protected_exports_list"\s*:\s*"android\/abi_gki_protected_exports_aarch64",\s*$//;' ./common/BUILD.bazel
        fi

        # Commit changes to avoid dirty state during build
        cd ${{ github.workspace }}/kernel/common
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Wild: Clean Dirty Flag"
