name: Setup Wild KSU
description: Download and configure Wild KSU with version tracking

runs:
  using: composite
  steps:
    - name: Download Wild KSU
      shell: bash
      working-directory: ${{ github.workspace }}/kernel
      run: |
        mv "$GITHUB_WORKSPACE/Wild_KSU" ./
        ./setup.sh

    - name: Enable KernelSU Config
      shell: bash
      working-directory: ${{ github.workspace }}/kernel
      run: |
        cat >> "${{ github.workspace }}/wild_gki.fragment" << 'EOF'
        # KernelSU Configuration
        CONFIG_KSU=y
        EOF
    
    - name: Extract KSU Version Info
      id: ksu-version
      shell: bash
      working-directory: ${{ github.workspace }}/kernel/Wild_KSU
      run: |
        # Extract and export KSU version info
        KSU_GIT_VERSION=$(git rev-list --count HEAD 2>/dev/null)
        KSU_GIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null)
        KSU_COMMIT=$(git rev-parse --short HEAD 2>/dev/null)
        KSU_VERSION=$((30000 + KSU_GIT_VERSION))
        
        echo "KSU_GIT_TAG=$KSU_GIT_TAG" >> $GITHUB_ENV
        echo "KSU_VERSION=$KSU_VERSION" >> $GITHUB_ENV
        echo "KSU_COMMIT=$KSU_COMMIT" >> $GITHUB_ENV
