name: 'Setup Audio Modules'
description: 'Configure SND audio modules for vTomsonek variant'
inputs:
  android_version:
    description: 'Android version'
    required: true
  kernel_version:
    description: 'Kernel version'
    required: true
  sublevel:
    description: 'Kernel sublevel'
    required: true
  os_patch_level:
    description: 'OS patch level'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure SND Audio Modules
      shell: bash
      working-directory: ${{ github.workspace }}/kernel
      run: |
        cat >> "${{ github.workspace }}/wild_gki.fragment" << 'EOF'
        # Sound Configuration
        CONFIG_SND=y
        CONFIG_SND_DRIVERS=y
        CONFIG_SND_PCM=y
        CONFIG_SND_TIMER=y
        CONFIG_SND_DYNAMIC_MINORS=y
        CONFIG_SND_PROC_FS=y
        CONFIG_SND_ALOOP=m
        CONFIG_USB_GADGET=y
        CONFIG_CONFIGFS_FS=y
        CONFIG_USB_CONFIGFS=y
        CONFIG_USB_LIBCOMPOSITE=m
        CONFIG_USB_AUDIO=m
        CONFIG_USB_CONFIGFS_F_UAC1=y
        CONFIG_USB_CONFIGFS_F_UAC2=y
        EOF

        # Add audio modules to gki modules list
        echo "drivers/usb/gadget/legacy/g_audio.ko" >> common/android/gki_aarch64_modules
        echo "sound/drivers/snd-aloop.ko" >> common/android/gki_aarch64_modules

        if [[ -f common/modules.bzl ]]; then
          # Insert audio modules into the module list based on version
          if [[ "${{ inputs.android_version }}" == "android14" && "${{ inputs.kernel_version }}" == "5.15" && ${{ inputs.sublevel }} -le 110 && "${{ inputs.os_patch_level }}" != "2023-09" ]] \
          || [[ "${{ inputs.android_version }}" == "android14" && "${{ inputs.kernel_version }}" == "6.1" && ${{ inputs.sublevel }} -le 25 && "${{ inputs.os_patch_level }}" != "2023-09" ]]; then
            # For older kernel builds
            sed -i '/COMMON_GKI_MODULES_LIST = \[/,/^[[:space:]]*\]/{/^[[:space:]]*\]$/i\    "sound/drivers/snd-aloop.ko",
            }' common/modules.bzl
            sed -i '/COMMON_GKI_MODULES_LIST = \[/,/^[[:space:]]*\]/{/^[[:space:]]*\]$/i\    "drivers/usb/gadget/libcomposite.ko",
            }' common/modules.bzl
            sed -i '/COMMON_GKI_MODULES_LIST = \[/,/^[[:space:]]*\]/{/^[[:space:]]*\]$/i\    "drivers/usb/gadget/legacy/g_audio.ko",
            }' common/modules.bzl
          else
            # For newer kernel builds
            sed -i '/_COMMON_GKI_MODULES_LIST = \[/,/^[[:space:]]*\]/{/^[[:space:]]*\]$/i\    "sound/drivers/snd-aloop.ko",
            }' common/modules.bzl
            sed -i '/_COMMON_GKI_MODULES_LIST = \[/,/^[[:space:]]*\]/{/^[[:space:]]*\]$/i\    "drivers/usb/gadget/libcomposite.ko",
            }' common/modules.bzl
            sed -i '/_COMMON_GKI_MODULES_LIST = \[/,/^[[:space:]]*\]/{/^[[:space:]]*\]$/i\    "drivers/usb/gadget/legacy/g_audio.ko",
            }' common/modules.bzl
          fi
          
          # Verify injection success
          if grep -q '"sound/drivers/snd-aloop.ko"' common/modules.bzl && \
            grep -q '"drivers/usb/gadget/libcomposite.ko"' common/modules.bzl && \
            grep -q '"drivers/usb/gadget/legacy/g_audio.ko"' common/modules.bzl && \
            grep -q '"drivers/usb/gadget/configfs.ko"' common/modules.bzl; then
            echo "✓ Audio modules injection: successfully added all modules to list"
          else
            echo "✗ Audio modules injection: failed to add one or more modules"
            exit 1
          fi
        fi

        # ABI compare bypass per kernel/android version
        if [[ "${{ inputs.android_version }}" == "android12" && "${{ inputs.kernel_version }}" == "5.10" ]]; then
          sed -i 's/^\s*exit 1$/    echo "Who Cares? Bypassing Now!"/' build/abi/compare_to_symbol_list
        elif [[ "${{ inputs.android_version }}" == "android13" && "${{ inputs.kernel_version }}" == "5.10" ]]; then
          sed -i 's/^\s*exit 1$/    echo "Who Cares? Bypassing Now!"/' build/kernel/abi/compare_to_symbol_list
        elif [[ "${{ inputs.android_version }}" == "android13" && "${{ inputs.kernel_version }}" == "5.15" ]]; then
          sed -i 's/^\s*exit 1$/    echo "Who Cares? Bypassing Now!"/' build/kernel/abi/compare_to_symbol_list
        elif [[ "${{ inputs.android_version }}" == "android14" && "${{ inputs.kernel_version }}" == "5.15" ]]; then
          perl -i -pe 's/^(\s*)return 1$/$1print("Who Cares? Bypassing Now!")\n$1return 0/g if /if missing_symbols:/../return 1/' build/kernel/abi/check_buildtime_symbol_protection.py
        elif [[ "${{ inputs.android_version }}" == "android14" && "${{ inputs.kernel_version }}" == "6.1" ]]; then
          perl -i -pe 's/^(\s*)return 1$/$1print("Who Cares? Bypassing Now!")\n$1return 0/g if /if missing_symbols:/../return 1/' build/kernel/abi/check_buildtime_symbol_protection.py
        elif [[ "${{ inputs.android_version }}" == "android15" && "${{ inputs.kernel_version }}" == "6.6" ]]; then
          perl -i -pe 's/^(\s*)return 1$/$1print("Who Cares? Bypassing Now!")\n$1return 0/g if /if missing_symbols:/../return 1/' build/kernel/abi/check_buildtime_symbol_protection.py
        fi
