name: 'Build Kernel'
description: 'Builds kernel using legacy build.sh or Bazel (kleaf)'

runs:
  using: composite
  steps:
    - shell: bash
      working-directory: ${{ github.workspace }}/kernel
      run: |
        set -euo pipefail
        if [ -f "build/build.sh" ]; then
          #SKIP_MRPROPER=1 
          GKI_DEFCONFIG_FRAGMENT="$GITHUB_WORKSPACE/wild_gki.fragment" BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
        else
          cp "$GITHUB_WORKSPACE/wild_gki.fragment" common/arch/arm64/configs/wild_gki.fragment
          tools/bazel build --config=release --stamp --notrim --defconfig_fragment=//common:arch/arm64/configs/wild_gki.fragment //common:kernel_aarch64_dist
        fi
