name: Kernel Config - A13 5.15

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:
    inputs: {}

jobs:
  build-kernels-a13-5-15:
    name: "5.15.${{ matrix.sub_level }}-android13-${{ matrix.os_patch_level }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - sub_level: "41"
            os_patch_level: "2022-06"
          - sub_level: "41"
            os_patch_level: "2022-07"
          - sub_level: "41"
            os_patch_level: "2022-08"
          - sub_level: "41"
            os_patch_level: "2022-09"
          - sub_level: "41"
            os_patch_level: "2022-10"
          - sub_level: "41"
            os_patch_level: "2022-11"
          - sub_level: "74"
            os_patch_level: "2022-12"
          - sub_level: "74"
            os_patch_level: "2023-01"
          - sub_level: "78"
            os_patch_level: "2023-02"
          - sub_level: "78"
            os_patch_level: "2023-03"
          - sub_level: "94"
            os_patch_level: "2023-04"
          - sub_level: "94"
            os_patch_level: "2023-05"
          - sub_level: "104"
            os_patch_level: "2023-06"
          - sub_level: "104"
            os_patch_level: "2023-07"
          - sub_level: "119"
            os_patch_level: "2023-08"
          - sub_level: "119"
            os_patch_level: "2023-09"
          - sub_level: "123"
            os_patch_level: "2023-10"
          - sub_level: "123"
            os_patch_level: "2023-11"
          - sub_level: "137"
            os_patch_level: "2023-12"
          - sub_level: "137"
            os_patch_level: "2024-01"
          - sub_level: "144"
            os_patch_level: "2024-02"
          - sub_level: "144"
            os_patch_level: "2024-03"
          - sub_level: "148"
            os_patch_level: "2024-04"
          - sub_level: "148"
            os_patch_level: "2024-05"
          - sub_level: "149"
            os_patch_level: "2024-06"
          - sub_level: "149"
            os_patch_level: "2024-07"
          - sub_level: "151"
            os_patch_level: "2024-08"
          - sub_level: "153"
            os_patch_level: "2024-09"
          - sub_level: "167"
            os_patch_level: "2024-11"
          - sub_level: "170"
            os_patch_level: "2025-01"
          - sub_level: "178"
            os_patch_level: "2025-03"
          - sub_level: "180"
            os_patch_level: "2025-05"
          - sub_level: "185"
            os_patch_level: "2025-07"
          - sub_level: "189"
            os_patch_level: "2025-09"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android13"
      kernel_version: "5.15"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}