name: Kernel Config - A14 5.15

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:
    inputs: {}

jobs:
  build-kernels-a14-5-15:
    name: "5.15.${{ matrix.sub_level }}-android14-${{ matrix.os_patch_level }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - sub_level: "110"
            os_patch_level: "2023-06"
          - sub_level: "110"
            os_patch_level: "2023-08"
          - sub_level: "110"
            os_patch_level: "2023-09"
          - sub_level: "131"
            os_patch_level: "2023-11"
          - sub_level: "137"
            os_patch_level: "2024-01"
          - sub_level: "144"
            os_patch_level: "2024-02"
          - sub_level: "144"
            os_patch_level: "2024-03"
          - sub_level: "148"
            os_patch_level: "2024-04"
          - sub_level: "148"
            os_patch_level: "2024-05"
          - sub_level: "149"
            os_patch_level: "2024-06"
          - sub_level: "153"
            os_patch_level: "2024-07"
          - sub_level: "158"
            os_patch_level: "2024-08"
          - sub_level: "164"
            os_patch_level: "2024-09"
          - sub_level: "167"
            os_patch_level: "2024-11"
          - sub_level: "170"
            os_patch_level: "2025-01"
          - sub_level: "178"
            os_patch_level: "2025-03"
          - sub_level: "180"
            os_patch_level: "2025-05"
          - sub_level: "185"
            os_patch_level: "2025-07"
          - sub_level: "192"
            os_patch_level: "2025-10"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android14"
      kernel_version: "5.15"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}